// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/welcome","name":"welcome","icon":"smile","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/Survey","name":"Survey","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"Weather","path":"/categories/weather","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/categories/tools","name":"Tools","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/categories/tools","redirect":"/categories/tools/tool1","parentId":"6","id":"7"},"8":{"path":"/categories/tools/tool1","name":"Tool-1","parentId":"6","id":"8"},"9":{"path":"/categories/tools/tool2","name":"Tool-2","parentId":"6","id":"9"},"10":{"name":"list.table-list","icon":"table","path":"/list","parentId":"ant-design-pro-layout","id":"10"},"11":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"11"},"12":{"path":"*","layout":false,"id":"12"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': require('./EmptyRoute').default,
'2': require('@/pages/User/Login/index.tsx').default,
'3': require('@/pages/Welcome.tsx').default,
'4': require('@/pages/PrivacyRiskSurvey.tsx').default,
'5': require('@/pages/Category_Weather/index.tsx').default,
'6': require('./EmptyRoute').default,
'7': require('./EmptyRoute').default,
'8': require('@/pages/Category_TOOL_1.tsx').default,
'9': require('@/pages/Category_TOOL_2.tsx').default,
'10': require('@/pages/TableList/index.tsx').default,
'11': require('./EmptyRoute').default,
'12': require('@/pages/404.tsx').default,
'ant-design-pro-layout': require('D:/PycharmProjects/myapp/frontend/src/.umi-test/plugin-layout/Layout.tsx').default,
},
  };
}
