// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'D:/PycharmProjects/myapp/frontend/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import TableOutlined from 'D:/PycharmProjects/myapp/frontend/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, TableOutlined };
