"""empty message

Revision ID: c265c429f330
Revises: 
Create Date: 2025-01-21 10:57:31.590906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c265c429f330'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('weather')
    op.drop_table('user_responses_weather')
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prolific_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('daily_time_spent', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('frequently_use_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sensitive_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sensitive_type_other', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('read_policy', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('familiar_with_perm', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('leak_actions', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('leak_actions_other', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('risk_attitude_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('risk_attitude_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('risk_attitude_3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('risk_attitude_4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prefer_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('thoughts', sa.String(length=200), nullable=True))
        batch_op.drop_column('gender')
        batch_op.drop_column('sensitive')
        batch_op.drop_column('age')
        batch_op.drop_column('readtime')
        batch_op.drop_column('time')
        batch_op.drop_column('familiarpermission')
        batch_op.drop_column('leakreact')
        batch_op.drop_column('education')
        batch_op.drop_column('type')
        batch_op.drop_column('familiar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('familiar', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('education', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('leakreact', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('familiarpermission', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('time', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('readtime', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sensitive', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('gender', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('thoughts')
        batch_op.drop_column('prefer_type')
        batch_op.drop_column('risk_attitude_4')
        batch_op.drop_column('risk_attitude_3')
        batch_op.drop_column('risk_attitude_2')
        batch_op.drop_column('risk_attitude_1')
        batch_op.drop_column('leak_actions_other')
        batch_op.drop_column('leak_actions')
        batch_op.drop_column('familiar_with_perm')
        batch_op.drop_column('read_policy')
        batch_op.drop_column('sensitive_type_other')
        batch_op.drop_column('sensitive_type')
        batch_op.drop_column('frequently_use_type')
        batch_op.drop_column('daily_time_spent')
        batch_op.drop_column('prolific_id')

    op.create_table('user_responses_weather',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('app_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('answer', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('weather',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('app_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('answer', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('contact')
    # ### end Alembic commands ###
