"""empty message

Revision ID: ff745c970678
Revises: 
Create Date: 2025-01-18 09:08:01.214550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff745c970678'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('user_name', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=100), nullable=False),
    sa.Column('education', sa.String(length=100), nullable=False),
    sa.Column('familiar', sa.Boolean(), nullable=False),
    sa.Column('time', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('sensitive', sa.String(length=100), nullable=False),
    sa.Column('readtime', sa.String(length=100), nullable=False),
    sa.Column('familiarpermission', sa.String(length=100), nullable=False),
    sa.Column('leakreact', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=21), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('surveys')
    # ### end Alembic commands ###
